### ISSUE TITLE
Incorrect link to account details

### ISSUE THREAD

**Issue by ixtlanian** [thycotic/ss-docs#114]
Document: (https://docs.thycotic.com/ss/10.9.0/secret-server-setup/licensing/licensing-faq/index.md)

The documentation states: "_the license information will remain available to you from your account at my.thycotic.com_"
my.thycotic.com simply redirects to thycotic.com
The correct URL is https://thycotic.force.com/

**Comment by wsprunk-thycotic** [comment]
Fixed in 11.0
