### ISSUE TITLE
Missing references

### ISSUE THREAD

**Issue by ixtlanian** [thycotic/ss-docs#115]
Document: (https://docs.thycotic.com/ss/10.9.0/secret-server-setup/licensing/licensing-faq/index.md)

The documentation states the following:
"_...there is an offline option for activating licenses. (See the Demo movie above for the offline process - also note the offline=true option described below if you have trouble activating offline)_"
1. There is no demo movie referenced in the document
2. There is no explanation of the offline=true setting

**Comment by wsprunk-thycotic** [comment]
Fixed in 11.0
