### ISSUE TITLE
The user interface has updated for this section, many of the configuration options have new names.  Now it looks like the picture below.  It is also accessed through Admin-> Directory Services not Admin-> Active Directory.  I was updating our training and saw that doc was out of step too.

### ISSUE THREAD

**Issue by mbuescher-thycotic** [thycotic/ss-docs#116]
Document: (https://docs.thycotic.com/ss/10.9.0/directory-services/active-directory/configuring-active-directory)

![image](https://user-images.githubusercontent.com/77462974/104644670-0d0fba00-567c-11eb-922a-bc10af66ab6a.png)

**Comment by wsprunk-thycotic** [comment]
Duplicate of 204565. Closing.
