### ISSUE TITLE
Incorrect navigation

### ISSUE THREAD

**Issue by ixtlanian** [thycotic/ss-docs#119]
Document: (https://docs.thycotic.com/ss/10.9.0/directory-services/active-directory/configuring-active-directory/index.md)

The document consistently mentions to go to **Admin >> Active Directory**. Such Admin page does not exist. It is **Admin >> Directory Services**. Other references should be fixed as well as further steps look different in v10.9

**Comment by wsprunk-thycotic** [comment]
Fixed in 11.0
