### ISSUE TITLE
Port 9354 is not used anymore

### ISSUE THREAD

**Issue by ixtlanian** [thycotic/ss-docs#125]
Document: (https://docs.thycotic.com/ss/10.9.0/distributed-engines/index.md)
Document: (https://docs.thycotic.com/ss/10.9.0/secret-server-cloud/quick-start/index.md)

According to case 00395153, port 9354 is a legacy port, which is not used by SSC anymore. Please remove the respective mentions of it from both listed documents.

**Comment by wsprunk-thycotic** [comment]
Fixed.
