### ISSUE TITLE
The Python and Ruby documents are switched.

### ISSUE THREAD

**Issue by jagger** [thycotic/ss-docs#152]
Sending these links to customers is confusing as the link for Python examples says ruby in the link and vice versa.

Document: (https://docs.thycotic.com/ss/10.9.0/api-scripting/soap-ruby-example-code)
Document: (https://docs.thycotic.com/ss/10.9.0/api-scripting/soap-python-example-code)

**Comment by wsprunk-thycotic** [comment]
Fixed
