### ISSUE TITLE
Incomplete permissions listed

### ISSUE THREAD

**Issue by ixtlanian** [thycotic/ss-docs#154]
Document: (https://docs.thycotic.com/ss/10.9.0/remote-password-changing/rpc-sql-server/index.md)

Privileged secret for MS SQL also requires **Control Server** permission (https://docs.microsoft.com/en-us/sql/t-sql/statements/alter-login-transact-sql?view=sql-server-ver15) for changing the target logins that are members of the **sysadmin** fixed server role or grantees of CONTROL SERVER permission.

**Comment by wsprunk-thycotic** [comment]
Fixed. Published later today.
