### ISSUE TITLE
Please update the sample XML on the article

### ISSUE THREAD

**Issue by youresofunny** [thycotic/ss-docs#176]
Document: (https://docs.thycotic.com/ss/10.9.0/secret-import-and-export/importing-secrets)

The sample XML article on this page is producing an error: Invalid XML
This is because the second line has invalid tag for import: "%3E"

<ImportFile xmlns:xsi="[http://www.w3.org/2001/XMLSchema-instance"](http://www.w3.org/2001/XMLSchema-instance) xmlns:xsd="http://www.w3.org/2001/XMLSchema"%3E

**Comment by wsprunk-thycotic** [comment]
Fixed. Will appear on Friday.
