### ISSUE TITLE
Download links to the v1.5 SDKs are broken. Please Fix.

### ISSUE THREAD

**Issue by altgss** [thycotic/ss-docs#181]
Document: (https://docs.thycotic.com/ss/10.9.0/api-scripting/sdk-downloads/index.md)

links under this section are broken:
SDK Client version 1.5.0

Release Notes
Cache improvements
Stability improvements

Downloads
Windows x64 (broken)
MacOS x64 (broken)
Linux x64 (including RHEL 7+) (broken)
Red Hat Enterprise Linux 6 x64

**Comment by wsprunk-thycotic** [comment]
This is fixed and will be published this Friday.
