### ISSUE TITLE
Link to Com + not working

### ISSUE THREAD

**Issue by mattboyce2000** [thycotic/ss-docs#183]
Document: (https://docs.thycotic.com/ss/10.9.0/discovery/general-information/discovery-account-permissions)

The link to Com + https://thycotic.force.com/support/s/article/ka037000000HtkmAAC/COMPlus-Depenency-Scanner no longer works (or it does but not to my partner account). I have tried this link without logging in and it is not possible to access without a logon. 

Also, Are we able to detail the requirements for IIS discovery on Secret Server Cloud. As far as I am aware this needs the Distributed Engine to run in the discovery account context. We don't appear to have anything detailing this, also changing the user context on the service may have knock on effects such as folder permissions needing changes etc. Is it possible to detail these?

**Comment by wsprunk-thycotic** [comment]
The article has been returned to available status and will be move to the TDP in the near future. Moved the second paragraph to a new item.
