### ISSUE TITLE
Dead link

### ISSUE THREAD

**Issue by zdechaine** [thycotic/ss-docs#210]
Document: (https://docs.thycotic.com/ss/11.0.0/api-scripting/configuring-winrm-powershell/index.md)

The "Powershell Remoting Security Considerations" link is dead and should point to here, I believe: https://docs.microsoft.com/en-us/powershell/scripting/learn/remoting/winrmsecurity?view=powershell-7.1

**Comment by wsprunk-thycotic** [comment]
Fixed. Will appear in this week's update on Friday.
