### ISSUE TITLE
ServiceNow - Incorrect domain name format

### ISSUE THREAD

**Issue by ManBearPig185** [thycotic/ss-docs#217]
Document: (https://docs.thycotic.com/ss/11.0.0/ticketing-system-integration/servicenow-integration/index.md)

Please modify the "Instance Name" to "Domain Name" and remove the HTTPS:// from it. The domain name should only be instance name.service-now.com (dev5859.service-now.com) and NOT this https://instance name.service-now.com. 

This is causing confusion. 

Thanks,
Jorge

**Comment by wsprunk-thycotic** [comment]
Fixed. Will appear with next update.
