### ISSUE TITLE
Will & cannot in same sentence.

### ISSUE THREAD

**Issue by mcontatore** [thycotic/ss-docs#225]
Document: (https://docs.thycotic.com/ss/11.0.0/secret-server-cloud/
![DocCapture](https://user-images.githubusercontent.com/78883522/132548775-af893cd1-8d5d-4fa4-a825-0d60c3d5d7ad.PNG)
quick-start)

Note: This is the backup admin account that you may need in a “break the glass” or unlimited admin situation. Thycotic recommends you store the password in a secured physical location such as a safe or locked file cabinet. You can reset the password using an email reset, but if this password is forgotten or you no longer have access to the email account, Thycotic will cannot reset this password.

**Comment by wsprunk-thycotic** [comment]
Fixed. Appears in next update.
