### ISSUE TITLE
Incorrect version requirement statement

### ISSUE THREAD

**Issue by mcontatore** [thycotic/ss-docs#226]
Document: (https://prod.homer.thycotic.net/ss/11.0.0/secret-launchers/remote-desktop-launchers/browser-configuration/index.md)

We specify that .NET 4.8+ is required for the SS related components, then here specify the lower unsupported version:

Firefox Configuration: Firefox requires a helper add-on application to run the RD and PuTTY launchers. The Microsoft .Net Framework Assistant add-on and .NET framework version 4.5.1 SP1 needs to be installed.
Chrome Configuration: If using ClickOnce, Chrome requires a Helper Add-on application to run the RDP and PuTTY Launcher. The ClickOnce add-on for Google Chrome Add-on needs to be installed. The launcher requires .NET framework version 4.5.1 SP1 as well.

**Comment by wsprunk-thycotic** [comment]
Fixed. Pub on Friday
