### ISSUE TITLE
Add context about "Go to Admin". Where is this?

### ISSUE THREAD

**Issue by docdawning** [thycotic/ss-docs#228]
Document: (https://docs.thycotic.com/ss/10.8.0/secret-server-setup/installation/enabling-sql-server-encryption)

The statement "Go to Admin > See All. The admin panel appears." is ambiguous. Go to "Admin" of what? Where? Add context please.

**Comment by wsprunk-thycotic** [comment]
Thanks for the input. Admin is on the main menu on the left.
