### ISSUE TITLE
Old information

### ISSUE THREAD

**Issue by dvanleur** [thycotic/ss-docs#232]
Document: (https://docs.thycotic.com/ss/10.8.0/secret-server-cloud/architecture/index.md)

This documentation containts old information, there is a newer version but not availible on the documentation website.

**Comment by danigran** [comment]
Current Architecture diagrams are under the Architecture documentation section, accessible via the Architecture drop-down menu on the doc portal:
![image](https://user-images.githubusercontent.com/46493756/133618975-f832f51a-5f89-4834-af00-9bfc556d59db.png)
The drop-down is available independent of product versions.

Stale document content for older product versions might contain outdated diagrams, as those were a snap-shot in time pertaining to that particular release when it went live.
